version: "3"

services:
  embeddings-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
    command: python embeddings.py
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
